### ISSUE TITLE
Usage of the Fixups in shell scripts

### ISSUE THREAD

**Issue by bonelifer** [garybuhrmaster/tv_grab_zz_sdjson_sqlite#11]
I know it can be done, but I'm not sure how to do this in shell scripts. I'm using Ubuntu 14.04. If I understand correctly I need to use: NO_XMLTV_NS_TOTAL_SEASONS for .27-fixes?  Right now for say Johnny Carson, I get the current year of 2017, instead of the date the show originally aired. Before my Mythbuntu 12.04 install drive failed I was using the mfdb-json grabber and it was properly filling the right dates. I'm assuming this fixup would fix this issue.

**Comment by garybuhrmaster** [comment]
It depends on your shell, and that question is best asked in the appropriate forum(s) regarding your shell experts, but the general answer is that one can either use EXPORT, as in:

```export TV_GRAB_TARGET_APPLICATION_FIXUPS=NO_XMLTV_NS_TOTAL_SEASONS```

before invoking the grabber, or, as shown in fixups.txt, something like the following which sets the environmental variable and invokes the script all on the same command line:

```TV_GRAB_TARGET_APPLICATION_FIXUPS=NO_XMLTV_NS_TOTAL_SEASONS tv_grab_zz_sdjson_sqlite```

Which will work better will depend on your particular requirements.

And, of course, I will remind you that MythTV 0.27 is no longer (officially) supported by that project, so you probably need to schedule your upgrade at some point (but that is a different concern).
