### ISSUE TITLE
tv_grab_zz_sdjson_sqlite puts wrong language id into xmltv 

### ISSUE THREAD

**Issue by ludi113** [garybuhrmaster/tv_grab_zz_sdjson_sqlite#13]
Hi, 

First of all, thanks for providing this useful tool to the community. However, I might have stumbled on a bug: The grabber seems to set the language id of each channel to "en". 

The quote below for example should indicate italian as language. 

`<tv generator-info-name="tv_grab_zz_sdjson_sqlite" generator-info-url="https://github.com/garybuhrmaster/tv_grab_zz_sdjson_sqlite" source-info-name="Schedules Direct" source-info-url="https://www.schedulesdirect.org">
 <channel id="I100806.json.schedulesdirect.org">
  <display-name lang="en">Rai 5 HD</display-name>
  <display-name lang="en">RAI5HD</display-name>
  <display-name lang="en">113</display-name>
  <icon src="https://s3.amazonaws.com/schedulesdirect/assets/stationLogos/s100806_h3_aa.png" width="360" height="270" />
 </channel>
 <channel id="I100855.json.schedulesdirect.org">
  <display-name lang="en">Radio Italia TV HD</display-name>
  <display-name lang="en">RITATVH</display-name>
  <display-name lang="en">135</display-name>
  <icon src="https://s3.amazonaws.com/schedulesdirect/assets/stationLogos/s100855_h3_aa.png" width="360" height="270" />
 </channel>
 <channel id="I102110.json.schedulesdirect.org">
  <display-name lang="en">Rai News 24 HD</display-name>
  <display-name lang="en">RAINWHD</display-name>
  <display-name lang="en">120</display-name>
  <icon src="https://s3.amazonaws.com/schedulesdirect/assets/stationLogos/s102110_h3_aa.png" width="360" height="270" />
...`

Could you please have a look? 

Thanks in advance.

**Comment by garybuhrmaster** [comment]
Thanks for the bug report. The source data for stations (i.e. channels) seems to (at least some of the time) have both a  "broadcastLanguage" and a "descriptionLanguage" which can (apparently) be different.  I need to check the definitions of those with the upstreams upstream to determine which to use if they are both specified for this purpose.

What lineup are you using so that I can check the results for your specific use case for my testing.

Thanks.

**Comment by garybuhrmaster** [comment]
For the history of this issue.  From Gracenote, the definitions are:

bcastLangs -- comma-separated list of language codes, indicating broadcast languages provided by station

edLangs -- comma-separated list of language codes, indicating editorial/description languages provided by station

In neither case are those values claimed to be directly related to the language of the display-name of the station/channel.  As the XMLTV dtd does not require a LANG attribute, I wonder if the correct solution is not to just eliminate the LANG attribute for channels/stations display-name entirely.  And what should happen if there is a list of multiple language codes (choose first?, or last?, as the list is not claimed to be ordered).  Thoughts welcome.

**Comment by garybuhrmaster** [comment]
Reviewing other grabbers, they do not (generally) include the lang attribute.  To be consistent with those other grabbers, commit https://github.com/garybuhrmaster/tv_grab_zz_sdjson_sqlite/commit/b4db3ff826cd56c5458cf2f5522769134ce1908d has removed it from being included.

Thanks for pointing out the issue
