### ISSUE TITLE
Grabber - schedulesDirect -- bug?

### ISSUE THREAD

**Issue by vskatusa** [garybuhrmaster/tv_grab_zz_sdjson_sqlite#18]
Hey, I use the following grabber to pull EPG from schedules direct:

"Internal: XMLTV: Multinational (Schedules Direct JSON web services with SQLITE)"

from configuration > Channel/EPG > EPG Grabber Modules

It ran successfully (according to debug log GUI). However, I do not see "60 Minutes" (EPG search as well as manual lookup) in the EPG which airs on say April 23rd.

To "isolate" the problem I generated the XMLTV "manually" using following command:

sudo tv_grab_zz_sdjson_sqlite --days 30 --output tv.xml
and I do see "60 Minutes" listed in tv.xml .

I have not changed the configuration. I discovered that EPG was wrong was when last episode of "60 Minutes" [ ENABLED recording of 60 Minutes every week ] did not record (April 16). Obviously TVheadend did not record because it could not find 60 Minutes in the EPG!

FYI before that I did record 1 episode of 60 minutes successfully!

Version info on UBUNTU 20.04 LTS:
HTS Tvheadend 4.3-2106~g9e1eb89be

Any tips to troubleshoot?

**Comment by garybuhrmaster** [comment]
If the raw xml shows the data you expect, that suggests tvheadend is not properly ingesting the data.

I do not use tvheadend, nor have much knowledge about it, but I do know that one has to explicitly associate the XMLTV id (called "channel" or "channel id" in the xml file) with the tvheadend EPG channel.  I also know that in some cases the upstream source(s) may change the XMLTV id, which may require you to manually adjust the associations.  That is something to check.

I would presume that tvheadend stores logs of their running of the XMLTV grabber, and should log its processing.  As I said, I don't have much knowledge about tvheadend, so I don't know if they provide sufficient information to help, or if there is a way to increase the logging verbosity.

There is a tvheadend forum where I would guess you might get some additional suggestions from people who run (and understand) tvheadend.

**Comment by garybuhrmaster** [comment]
Hopefully the tvheadend forums helped.  Closing this issue.
